language: python
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
python:
  - "3.7-dev"
install:
  - pip install -r requirements/travis.pip
env:
  - DJANGO_ENV=travis
script:
  - python manage.py test applications -v 2
